version: '3.8'

services:

  database:
    container_name: db_container
    image: "mongo:4.4.7"
    hostname: db_host
    volumes:
      - ./db_data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  flask:
    build: .
    container_name: flask_container
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./:/backend
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - database
    command: gunicorn --reload -b 0.0.0.0:8000 server:app

networks:
  backend:
    external: false
    name: backend
